[toolchain]
anchor_version = "0.28.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
fomo_contract = "GbsLgoBo4yX5V4LHtE7xA7i41R8uFB5P7oXUJMcNTxJi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
