[toolchain]
anchor_version = "0.28.0"

[features]
resolution = false
skip-lint = false

[programs.devnet]
fomo_contract = "3RYs4pJ6T1sKaVrxX8Fxfvje3QV13kuhTMcr444DJJEs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
